name: .NET Core CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: DeployDemoAppWithActions    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './Demo/Demo.Web'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '2.1.x'           # set this to the dot net version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          dotnet build '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' --configuration Release --no-restore
          dotnet publish '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/demoapp' 
          
      # Deploy to Azure Web apps
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/demoapp'
